CONST
	uSL_VERSION 2.0
END

RULE	event Mod.uScriptLibrary
	:action
		
		//Register Top level object
		U.uSL := getMachine("Mod/uScriptLibrary"):changeState(MOD, 0);
		U.uSL.VERSION := #uSL_VERSION;
		
		Return(1);
		
	:end
END

MACHINE "Mod/uScriptLibrary"

	STATE MOD
	
		RULE	event In
			:action
			
				//Allocate modules stack
				Modules := getFreeSel();
					
				//Call Configuration for standalone mod
				this:uCall(Mod.uScriptLibrary.Config, 0);
			
			:end
		END
		
		RULE	event Use
			condition E.module
			:action
			
				E.module_mach_name := sCat("Module/", E.module);
				E.module_mach := getMachine(E.module_mach_name):changeState(MODULE, 0);
				assert(E.module_mach);
			
				E.mc := allNumof(Modules);
					DIM(Modules, E.mc+1);
				setN(Modules, E.mc, E.module_mach);
			
			:end
		END
		
		#include "uSL/class_machine.mach"
		#include "uSL/Modules.h"
		
	END

END

