/* CLASS MEMMORY CONCEPT

|- registry_TOP -|
|- mapping_TOP  -|- registry_LOW []
                 |- mapping_LOW  [] ->

->|- pull_TOP   -|
                 |- pull_LOW [] -|
			                     |- var_stack
*/

RULE	event uSL.Class.FindClassTemplate
	:action
	
		E.template := sCat("uSL/Class/", E.class);
		E.mach := getMachine(E.template);
		assert(E.mach);
		Return(E.mach);
		
	:end
END

MACHINE "uSL/Module/Class"

	#include "uSL/module/initialize"

		RULE	event onInitialize
			:action
	
				//allocate topmost memmory
				__registry_TOP := getFreeSel();
					DIM(__registry_TOP, 1);
					
				__mapping_TOP := getFreeSel();
					DIM(__mapping_TOP, 1);
					
				E.__registry_LOW := getFreeSel();
					DIM(E.__registry_LOW, 0);
					
				E.__mapping_LOW := getFreeSel();
					DIM(E.__mapping_LOW, 0);
					
				setN(__registry_TOP, 0, E.__registry_LOW);
				setN(__mapping_TOP, 0, E.__mapping_LOW);
	
				U.uSL.Class := this;
				Debug("uSL Module Class initialized");
			
			:end
		END
	
	#include "uSL/module/body"
		
		#include "debug/module.class.debug"
		
		RULE	event PostInitialize
			#include "uSL/function/private"
			:action
			
				E.example := this:uCall(uSl.Class.FindClassTemplate, E.class := "Example");
				this:localEvent(RegisterClass, E.class := P.example);
			
			:end
		END
		
		RULE	event __FindClass
			#include "uSL/function/private"
			:action
			
				E.result := 0;
				
				E.rT_id := 0;
				E.rT_num := allNumOf(__registry_TOP);
				
				while
				(
					E.rT_id<E.rT_num,
					(
						E.rL := getN(__registry_TOP, E.rT_id);
						
						if
						(
							inSelection(E.rL, E.class),
							(
								E.result := 1;
								E.mL := getN(__mapping_TOP, E.rT_id);
								P.pT := getN(E.mL, indexOf(E.rL, E.class));
							)
						);
						
						chooseFirst
						(
							E.result,
								E.rT_id := E.rT_num,
							1,
								E.rT_id := E.rT_id + 1
						);
					)
				);
				
				Return(E.result);
			
			:end
		END
	
		RULE	event __AllocNewLow
			#include "uSL/function/private"
			:action
			
				E.top_id := allNumOf(E.top);
				
				assert(E.top_id < 256);
				
				E.low := getFreeSel();
					DIM(E.low, 0);
					
				DIM(E.top, E.top_id + 1);
				setN(E.top, E.top_id, E.low);
			
				Return(E.low);
				
			:end
		END
	
		RULE	event __SetTopLowMemmory
			#include "uSL/function/private"
			:action
			
				E.top_id := allNumOf(E.top) - 1;
				
				assert(E.top_id < 256);
			
				E.low := getN(E.top, E.top_id);
				
				if
				(
					allNumOf(E.low)=256,
						E.low := this:localEvent(__AllocNewLow, E.top := P.top);
				);
				
				Return(E.low);
				
			:end
		END
	
		RULE	event __RegisterClass
			#include "uSL/function/private"
			:action
			
				E.rL := this:localEvent(__SetTopLowMemmory, E.top := __registry_TOP);
				E.mL := this:localEvent(__SetTopLowMemmory, E.top := __mapping_TOP);
				
				
				E.rL_id := allNumOf(E.Rl);
				DIM(E.rL, E.rL_id + 1);
				setN(E.rL, E.rL_id, E.class);
				
				E.mL_id := allNumOf(E.mL);
				DIM(E.mL, E.mL_id + 1);
				
				E.pT := getFreeSel();
					DIM(E.pT, 1);
					
				E.pL := getFreeSel();
					DIM(E.pL, 0);
					
				setN(E.pT, 0, E.pL);
				setN(E.mL, E.mL_id, E.pT);
				
				this:localEvent(__Debug_Registred, E.class := P.class);
				
			:end
		END
	
		RULE	event RegisterClass
				condition E.class!=C.this //forbid self registring
			:action
			
				//Check E.class
				assert(E.class);
				
				E.isRegistred := this:localEvent(__FindClass, E.class := P.class);
				
				if
				(
					!E.isRegistred,
					(
						E.class:changeState(SELFTEST, 0);
						E.isClass := E.class:localEvent(isClass);
					)
				);
			
				chooseFirst
				(
					E.isRegistred,
						this:localEvent(__Debug_isRegistred, E.class := P.class),
					!E.isClass,
						this:localEvent(__Debug_isNotClass, E.class := P.class),
					1,
						this:localEvent(__RegisterClass, E.class := P.class);
				);
			
			:end
		END
	
	#include "uSL/module/end"
	
END