/* CLASS MEMMORY CONCEPT

|— registry_TOP
| |— registry_LOW [] - "uSL/class reference"
|
|- uType_mapper_TOP
|  |— uType_mapper_LOW [] - "uType()" integer code. Todo: make uType constant table in uSl.Class.Const.ini
|
|— mapper_TOP
| |— mapper_LOW []
|   |— pool_TOP
|     |— pool_LOW []
|       |— var_STACK

*/

RULE	event uSL.Class.FindClassTemplate
	:action
	
		E.template := sCat("uSL/Class/", E.class);
		E.mach := getMachine(E.template);
		assert(E.mach);
		Return(E.mach);
		
	:end
END

MACHINE "uSL/Module/Class"

	#include "uSL/module/initialize"

		RULE	event onInitialize
			:action
		
				//Initialize top levels and first low levels lists
				__registy_TOP := getFreeSel();
					DIM(__registy_TOP, 1);
					
				__mapper_TOP := getFreeSel();
					DIM(__mapper_TOP, 1);
					
				__uType_mapper_TOP := getFreeSel();
					DIM(__uType_mapper_TOP, 1);
					
				E.rL := getFreeSel();
					DIM(E.rL, 0);
					
				E.mL := getFreeSel();
					DIM(E.mL, 0);
					
				E.umL := getFreeSel();
					DIM(E.umL, 0);
					
				//Assign ll lists to tl lists
				setN(__registy_TOP, 0, E.rL);
				setN(__mapper_TOP, 0, E.mL);
				setN(__uType_mapper_TOP, 0, E.umL);
		
				U.uSL.Class := this;
				Debug("uSL Module Class initialized");
			
			:end
		END
	
	#include "uSL/module/body"
		
		#include "debug/module.class.debug"
		
		/*
			This method must be called for every class used by game before actually game start
			Arguments:
			E.class - stateMachine object - Class itself. Use uSL.Class.FindClassTemplate subroutine for find named class template in strategy subroutines
			E.uType - const nonnegative integer or 0 - valid uType identificator for hardcoded TJI classes (Ship, celestial, etc). Can be obtain by uType() object method
		*/
		RULE	event RegisterClass
				condition E.class!=C.this
			:action
				
				assert(E.class);
				
				E.isReg := 0;
				E.isClass := 0;
				E.isuType := 0;
				
				E.isReg := this:localEvent(__FindClass, E.class := P.Class);
				
				if
				(
					!E.isReg,
					(
						E.class:changeState(SELFTEST);
						E.isClass := E.class:localEvent(isClass);
					)
				);
				
				if
				(
					E.uType & !E.isReg,
						E.isuType := this:localEvent(__FindByuType, E.uType := P.uType)
				);
				
				chooseFirst
				(
					E.isReg,
						this:localEvent(__Debug_isRegistred, E.class := P.class),
					E.isClass,
						this:localevent(__Debug_isNotClass, E.class := P.class),
					E.isuType,
						this:localEvent(__Debug_isKnownuType, E.class := P.class),
					1,
						this:localEvent(__RegisterClass, E.class := P.class; E.uType := P.uType);
				);
				
			:end
		END
	
		RULE	event __FindClass
			#include "uSL/function/private"
			:action
			
				E.result := 0;
				
				E.rT_id := 0;
				E.rT_num := allNumOf(__registy_TOP);
				
				while
				(
					E.rT_id < E.rT_num,
					(
						E.rL := getN(__registy_TOP, E.rT_id);
						
						if
						(
							inSelection(E.rL, E.class),
							(
								E.result := 1;
								E.rL_id := indexOf(E.rL, E.class);
							)
						);
						
						chooseFirst
						(
							E.result,
								E.rT_id := E.rT_num,
							1,
								E.rT_id := E.rT_id + 1;
						);
						
					)
										
				);
			
				Return(E.result);
			
			:end
		END
		
		RULE	event __FindByuType
			#include "uSL/function/private"
			:action
				
				E.result := 0;
				
				E.umT_id := 0;
				E.umT_num := allNumOf(__uType_mapper_TOP);
				
				while
				(
					E.umT_id < E.umT_num,
					(
						E.umL := getN(__uType_mapper_TOP, E.umT_id);
						E.umL_id := 0;
						E.umL_num := allNumOf(E.umL);
						
						while
						(
							E.umL_id < E.umL_num,
							(
								if
								(
									E.uType = getN(E.umL, E.umL_id),
									(
										E.result := 1;
									)
								);
								
								chooseFirst
								(
									E.result,
										E.umL_id := E.umL_num,
									1,
										E.umL_id := E.umL_id + 1;
								);
							)
						);
						
						chooseFirst
						(
							E.result,
								E.rT_id := E.rT_num,
							1,
								E.rT_id := E.rT_id + 1;
						);
					)
				);
				
				Return(E.result);
				
			:end
		END
	
		RULE	event __AllocNewLow
			#include "uSL/function/private"
			:action
			
				E.top_id := allNumOf(E.top);
				
				assert(E.top_id < 256);
				
				E.low := getFreeSel();
					DIM(E.low, 0);
					
				DIM(E.top, E.top_id + 1);
				setN(E.top, E.top_id, E.low);
			
				Return(E.low);				
			
			:end
		END
	
		RULE	event __SetTopLow
			#include "uSL/function/private"
			:action
			
				E.top_id := allNumOf(E.top) - 1;
				
				assert(E.top_id < 256);
			
				E.low := getN(E.top, E.top_id);
				
				if
				(
					allNumOf(E.low)=256,
						E.low := this:localEvent(__AllocNewLow, E.top := P.top);
				);
				
				Return(E.low);
			
			:end
		END
				
		RULE	event __RegisterClass
			#include "uSL/function/private"
			:action
			
				E.rL := this:localEvent(__SetTopLow, E.top := __registy_TOP);
				E.mL := this:localEvent(__SetTopLow, E.top := __mapper_TOP);
				E.umL := this:localEvent(__SetTopLow, E.top := __uType_mapper_TOP);
				
				E.rL_id := allNumOf(E.rL);
				E.ml_id := allNumOf(E.mL);
				E.uml_id := allNumOf(E.umL);
				
				assert(E.rL_id=E.ml_id&E.rL_id = E.uml_id);
				
				DIM(E.rL, E.rL_id + 1);
				DIM(E.mL, E.ml_id + 1);
				DIM(E.umL, E.umL_id + 1);
				
				E.pT := getFreeSel();
					DIM(E.pT, 1);
					
				E.pL := getFreeSel();
					DIM(E.pL, 0);
				
				setN(E.umL, E.uml_id, E.uType);
				
				setN(E.pT, 0, E.pL);
				setN(E.mL, E.ml_id, E.pT);
				
				this:localEvent(__Debug_Registred, E.class := P.class);
			
			:end
		END
	
	#include "uSL/module/end"
	
END