MACHINE "uSL/Class/Location"

	#include "uSL/class/declaration"
	
	RULE	event __Constructor
		#include "uSL/function/private"
		:action
		
			_tjiObject := 0;
			Parent_Class := 0;
			Parent_ref := 0;
		
		:end
	END
	
	RULE	event __var
		:action
		
			if (!E.flag, E.flag := #uSL_CLASS_SETGET);
			
			_tjiObject := 		this:localEvent(__instvar, E.flag := P.flag; E.id := 1; E.value := _tjiObject);
			Parent_Class := 	this:localEvent(__instvar, E.flag := P.flag; E.id := 2; E.value := Parent_Class);
			Parent_ref := 		this:localEvent(__instvar, E.flag := P.flag; E.id := 3; E.value := Parent_ref);
		
		:end
	END
	
	RULE	event Create
		#include "uSL/class/instance"
		:action
			
			_tjiObject := E.location;
			Parent_Class := E.Parent_Class;
			Parent_ref := E.Parent_ref;
			
			//load fleets
			
		:end
		#include "uSL/class/end_instance"
	END
	
	#include "uSL/class/end"

END