/* CLASS MEMMORY CONCEPT

|- registry_TOP -|
|- mapping_TOP  -|- registry_LOW []
                 |- mapping_LOW  [] ->

->|- pull_TOP   -|
                 |- pull_LOW [] -|
			                     |- var_stack
*/

RULE	event uSL.Class.FindClassTemplate
	:action
	
		E.template := sCat("uSL/Class/", E.class);
		E.mach := getMachine(E.template);
		assert(E.mach);
		Return(E.mach);
		
	:end
END

MACHINE "uSL/Module/Class"

	#include "uSL/module/initialize"

		RULE	event onInitialize
			:action
				
				U.uSL.Class := this;
				Debug("uSL Module Class initialized");
			
			:end
		END
	
	#include "uSL/module/body"
		
		RULE	event PostInitialize
			#include "uSL/function/private"
			:action
			
				E.example := this:uCall(uSl.Class.FindClassTemplate, E.class := "Example");
				this:localEvent(RegisterClass, E.class := P.example);
			
			:end
		END
		
	
	#include "uSL/module/end"
	
END