MACHINE "uSL/Class/Fleet"

	#include "uSL/class/declaration"
	
	RULE	event __Constructor
		#include "uSL/function/private"
		:action
		
			__tjiobject := 0;
			location := 0;
			destination := 0;
			
		:end
	END
	
	RULE	event __Destructor
		#include "uSL/class/instance"
		:action
		
		:end
		#include "uSL/class/end_instance"
	END
	
	RULE	event __var
		:action
		
			if (!E.flag, E.flag := #uSL_CLASS_SETGET);
			
			__tjiobject := 	localEvent(__instvar, E.flag := P.flag; E.id := 1; E.value := __tjiobject);
			location :=		localEvent(__instvar, E.flag := P.flag; E.id := 2; E.value := location);
			destination :=	localEvent(__instvar, E.flag := P.flag; E.id := 3; E.value := destination);
		
		:end
	END

	RULE	event Create
		#include "uSL/class/instance"
		:action
		
			__tjiobject := E.fleet;
			location := 0;
			destination := 0;
		
		:end
		#include "uSL/class/end_instance"
	END
	
	#include "uSL/class/end"
	
END